// <auto-generated />
using System;
using ETBCaseProject.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ETBCaseProject.Repository.Migrations
{
    [DbContext(typeof(EtbDbContext))]
    partial class EtbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ETBCaseProject.Core.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1993, 8, 8, 20, 42, 1, 83, DateTimeKind.Local).AddTicks(9199),
                            CreatedDate = new DateTime(2023, 8, 8, 20, 42, 1, 83, DateTimeKind.Local).AddTicks(9221),
                            FullName = "Mehmet Yılmaz",
                            MailAddress = "mehmetyilmaz@gmail.com",
                            PhoneNumber = "05334567891"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1998, 8, 8, 20, 42, 1, 83, DateTimeKind.Local).AddTicks(9225),
                            CreatedDate = new DateTime(2023, 8, 8, 20, 42, 1, 83, DateTimeKind.Local).AddTicks(9226),
                            FullName = "Cenk Kılıç",
                            MailAddress = "cenkkilic@gmail.com",
                            PhoneNumber = "05354577891"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1983, 8, 8, 20, 42, 1, 83, DateTimeKind.Local).AddTicks(9228),
                            CreatedDate = new DateTime(2023, 8, 8, 20, 42, 1, 83, DateTimeKind.Local).AddTicks(9229),
                            FullName = "Mehmet Yılmaz",
                            MailAddress = "mehmetyilmaz@gmail.com",
                            PhoneNumber = "05334578681"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
